TravelAgenncyUI/Models/TourViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TravelAgenncyUI.Models
{
    public class TourViewModel
    {
        public int Id { get; set; }

        public string Hotel { get; set; }

        public string Telephone { get; set; }

        public int? ResortNights { get; set; }

        public double Price { get; set; }

        public string Valute { get; set; }

        public int? MaxAmountPeople { get; set; }

        public int? MinAmountPeople { get; set; }

        public float Rating { get; set; }

        public string MealType { get; set; } // allinclusive, ultra allinclusive, only breakfast and supper and other ...

        //public virtual FlightViewModel Flight { get; set; }

        public string LocationFirstFlight { get; set; } //country, city from we start tour

        public string LocationResortPlace { get; set; } //country, city where we resort/relax

        public string Flight { get; set; }


        public string Description { get; set; }
        public string TypeRoom { get; set; }

        public string Image { get; set; }

        public string FullIdentity => "Element" + this.Id;

        virtual public ICollection<string> ImageForGallaries { get; set; }

        public TourViewModel()
        {
            ImageForGallaries = new List<string>();
        }

        //public int Id { get; set; }

        //[Required(ErrorMessage = "Name can't be null")]
        //[StringLength(200, ErrorMessage = "Max count of symbols are 200")]
        //public string Name { get; set; }

        //[Range(1, 1000)]
        //public int? ResortNights { get; set; }
        //public string Price { get; set; }

        //[Range(1, 200, ErrorMessage = "Please enter a value bigger than {1}")]
        //public int? AmountPeople { get; set; }
        //public string Type { get; set; } // all inclusive or other
        //public string Location { get; set; }
        //public string Flight { get; set; }

        //public string Description { get; set; }

        //public string Image { get; set; }
    }
}

TravelAgenncyUI/Controllers/TourController.cs
using AutoMapper;
using Binbin.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using System.Web;
using System.Web.Compilation;
using System.Web.Mvc;
using TravelAgenncyUI.Models;
using TravelAgenncyUI.Utils.Helpers;
using TravelBLL.Filters;
using TravelBLL.Interfaces;
using TravelDAL.Entities;

namespace TravelAgenncyUI.Controllers
{
    public class TourController : Controller
    {
        private readonly ITourService _tourService;
        private readonly IMapper _mapper;

        //from DI
        public TourController(ITourService tourService, IMapper mapper)
        {
            _tourService = tourService;
            _mapper = mapper;
        }

        // GET: Tour
        //public ActionResult Index()
        //{
        //    return View();
        //}


        public ActionResult Index(string search)
        {
            ViewBag.Title = "TourStore";
            #region Manual mapping
            //var games = new List<GameViewModel>();
            //foreach (var item in _gameService.GetAllGames())
            //{
            //    games.Add(new GameViewModel
            //    {
            //        Id = item.Id,
            //        Name = item.Name,
            //        Description = item.Description,
            //        Price = item.Price,
            //        Year = item.Year//,
            //        //Developer = item.De
            //    });
            //} 
            #endregion

            var tour = _mapper.Map<List<TourViewModel>>(_tourService.GetAllTour(null));
            SetViewBag();
            if (String.IsNullOrEmpty(search))
            {
                return View(tour);
            }


            return View(tour.Where(x => x.Hotel.Contains(search)).ToList());

            // var developers = new[] { "Bethesda", "Rockstar", "Ubisoft" };
            // ViewBag.Developers = developers;

        }

        public ActionResult GetLocations()
        {
            return View();
        }

        public ActionResult Create()
        {
            //ViewBag.Locactions = GetLocationsString(_tourService.GetAllLocation());
            //ViewBag.Locactions = _tourService.GetAllLocation();
            //ViewBag.Flights = _tourService.GetAllFlight();
            SetViewBag();
            return View();
        }

        public List<string> GetLocationsString(IEnumerable<Location> list)
        {
            List<string> loc = new List<string>();

            foreach (var item in list)
            {
                loc.Add(item.City + ", " + item.Country);
            }

            return loc;
        }

        public ActionResult ToursPage()
        {
            SetViewBag();

            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(TourViewModel model, HttpPostedFileBase image)
        {
            // 1) якщо картинка:
            //    2) зберегти картинку на сервер
            // 2.1) конвертувати картинку
            //    3) записати шлях в модель
            if (!ModelState.IsValid)
            {
                return View();
            }

            if (image != null)
            {
                var fileName = Guid.NewGuid().ToString() + ".jpg";

                var bitmap = BitmapConvertor.Convert(image.InputStream, 200, 200);
                var serverPath = Server.MapPath($"~/Images/{fileName}");

                bitmap.Save(serverPath);
                model.Image = $"/Images/{fileName}";
            }

            await _tourService.AddTourAsync(_mapper.Map<Tour>(model));
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var tour = _tourService.GetTour(id);
            return View(_mapper.Map<TourViewModel>(tour));
        }

        [HttpPost]
        public ActionResult Edit()
        {
            return View();
        }

        public ActionResult Filter(string type, string value)
        {

            var filter = new TourFilter()
            {
                Name = value,
                Type = type
            };

            // predicate: x => x.Developer == Bogdan
            // predicate: x => x.Genre == RPG

            if (type == "location")
            {
                filter.Predicate = (x => x.Hotel == value);
            }
            else if (type == "flightcitystart")
            {
                filter.Predicate = (x => x.Flight.FlightDateToBegan == value);
            }
            else if (type == "flighttype")
            {
                filter.Predicate = (x => x.Flight.Type == value);
            }

            var filters = new List<TourFilter>();
            if (Session["TourFilter"] != null)
            {
                filters = Session["TourFilter"] as List<TourFilter>;
            }

            //var results = filters.GroupBy(
            // p => p.Name,
            // p => p.Type,
            // (key, g) => new { PersonId = key, Cars = g.ToList() });

            var found = filters.FirstOrDefault(f => f.Name == value && f.Type == type);
            if (found != null)
            {
                filters.Remove(found);
            }
            else
            {
                filters.Add(filter);
            }

            Session["TourFilter"] = filters;

            var games = _tourService.GetAllTour(filters);
            SetViewBag();

            return PartialView("ToursPartial", _mapper.Map<List<TourViewModel>>(games));
        }

        private void SetViewBag()
        {
            ViewBag.Tours = _mapper.Map<List<TourViewModel>>(_tourService.GetAllTour(null));//_tourService.GetAllTour(null);



            var tours = _mapper.Map<List<TourViewModel>>(_tourService.GetAllTour(null));

            for (int i = tours.Count - 1; i >= 6; i--)
            {
                tours.RemoveAt(i);
            }

            //int temp = 0;

            //foreach (var item in _tourService.GetAllTour(null))
            //{
            //    if (temp < 6)
            //    {
            //        tours.Add(item);
            //    }

            //    temp++;
            //}

            ViewBag.SomeDemoTours = tours;

            List<string> temptry = new List<string>() { "h", "e", "l", "p" };
            ViewBag.Locactions = _tourService.GetAllLocation().Select(x => x.City + ", " + x.Country);
            ViewBag.Flights = _tourService.GetAllFlight().Select(x => x.FlightDateToBegan + " at " + x.StartTimeHours);
            ViewBag.FlightType = _tourService.GetAllFlight().Select(x => x.Type);
           // ViewBag.FlightForChoose = _tourService.GetAllFlight().Select(x => x.Type + " (from " + x..City + ", " + x.LocationFirstFlight.City + " at " + x.LocationResortPlace.City + ", " + x.LocationResortPlace.City+ " )"); ;
        }
    }
}

TravelAgenncyUI/Views/Tour/Create.cshtml
@*@{
        ViewBag.Title = "Create";
    }

    <h2>Create</h2>*@


@model TravelAgenncyUI.Models.TourViewModel

@{
    //ViewBag.Title = "Create";
    ViewBag.Title = "Tour Store";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}
<div class="dashboard-wrapper">
    <div class="container pt-4">
        <div class="row mb-5">
            <h2 class="invisible">novisbl</h2>

            @using (Html.BeginForm("Create", "Tour", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
        <div class="form-horizontal mb-3">
            <h2>Create Tour</h2>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @*<div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>*@

            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ResortNights, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ResortNights, new { htmlAttributes = new { @type = "number", @min = "1", @max = "500", @value = "0", @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ResortNights, null, new { @type = "number" })
                </div>
            </div>

            @*<div class="form-group">
            @Html.LabelFor(model => model.AmountPeople, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AmountPeople, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AmountPeople, "", new { @class = "text-danger" })
            </div>
        </div>*@

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group col-md-10 my-image-chooser">
                <div>
                    <input type="radio" data-input-to-show="#localImg" data-input-to-hide="#urlimage" onchange="ChoosenUrlImg(this)" name="img-group" id="radioUrlImg" />
                    <label for="radioUrlImg">Image Url</label>
                </div>
                <div>
                    <input type="radio" data-input-to-show="#urlimage" data-input-to-hide="#localImg" onchange="ChoosenUrlImg(this)" name="img-group" id="radioFileImg" />
                    <label for="radioFileImg">Local Image</label>
                </div>
                <div class="w-100">
                    <input type="file" accept=".jpg, .png, .jpeg, .gif, .bmp, .tif, .tiff|image/*" name="image" id="localImg" placeholder="choose" /> @**@
                    <input type="text" name="image" id="urlimage" placeholder="enter URL" />
                </div>
            </div>
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.LocationFirstFlight, new SelectList(ViewBag.Locactions), "Choose location", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LocationFirstFlight, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.LocationResortPlace, new SelectList(ViewBag.Locactions), "Choose location", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LocationResortPlace, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-10">
                @*@Html.DropDownList("Flights", new SelectList(ViewBag.Flights), "Choose flight", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Flight, "", new { @class = "text-danger" })*@
                @Html.DropDownListFor(model => model.Flight, new SelectList(ViewBag.FlightForChoose), "Choose flights", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Flight, "", new { @class = "text-danger" })

                @*<div class="col-md-10">
                @Html.EditorFor(model => model.Flight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Flight, "", new { @class = "text-danger" })
            </div>*@
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" id="MyCreateInput" class="btn btn-default" />
                </div>
                <div class="col-md-10 text-center m-t-20">
                    @Html.ActionLink("Back to List", "Index")
                </div>
            </div>

        </div>
            }

            @*<div>
                @Html.ActionLink("Back to List", "Index")
            </div>*@
        </div>
    </div>
</div>

TravelAgenncyUI/Views/Tour/Edit.cshtml
@*@{
        ViewBag.Title = "Edit";
    }

    <h2>Edit</h2>*@

@model TravelAgenncyUI.Models.TourViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<div class="dashboard-wrapper">
    <div class="container pt-4">
        <div class="row">
            <h2>Edit</h2>

            @using (Html.BeginForm())
            {
        <div class="form-horizontal">
            <h4>TourViewModel</h4>
            <hr />

            @*<div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>*@

            @*<div class="form-group">
                @Html.LabelFor(model => model.Flight, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Flight, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Flight, "", new { @class = "text-danger" })
                </div>
            </div>*@

            @*<div class="form-group">
                @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
                </div>
            </div>*@


            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                </div>
            </div>

            @*<div class="form-group">
                @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Genre, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Developer, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Developer, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Developer, "", new { @class = "text-danger" })
                </div>
            </div>*@

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
            }

            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div>
    </div>
</div>

TravelAgenncyUI/Views/Tour/GetLocations.cshtml
@*@{
        ViewBag.Title = "GetLocations";
    }

    <h2>GetLocations</h2>*@


@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>GetLocations</title>
</head>
<body>
    <div>
    </div>
</body>
</html>

TravelAgenncyUI/Views/Tour/ToursPartial.cshtml
@model  List<TravelAgenncyUI.Models.TourViewModel>

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-12 col-sm-6 col-md-4 col-lg-3 travel-card">
            <div class="card">
                <img class="card-img-top img-fluid p-2" src="@item.Image" alt="Card image cap">
                <div class="card-body">
                    <h3 class="card-title">@item.Hotel</h3>
                    <p class="card-text">@item.Description</p>
                    <p class="card-text">Location: <strong>@item.Flight</strong></p>
                    <p class="card-text">Flight from: <strong>@item.Flight</strong></p>
                    <p class="card-text">@item.Price</p>
                    @*<a href="/Tour/Edit" class="btn btn-primary">Edit</a>*@
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                </div>
            </div>
        </div>
    }
</div>